# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# Synopsis: Configuration for PSRule.Rules.GitHub
apiVersion: github.com/microsoft/PSRule/v1
kind: ModuleConfig
metadata:
  name: PSRule.Rules.GitHub
spec:
  binding:
    targetName:
    - BranchName
    - RepositoryName
    targetType:
    - Type
  convention:
    include:
    - GitHub.ExpandRepository
  output:
    culture:
    - 'en'
  configuration:
    GitHub_BranchName_Format: ''
    GitHub_BranchName_Disallowed:
    - master
