

---
# Synopsis: Configuration for PSRule.Rules.GitHub
kind: ModuleConfig
metadata:
  name: PSRule.Rules.GitHub
spec:
  binding:
    targetName:
    - Name
    targetType:
    - Type
  configuration:
    GitHub_BranchName_Format: ''
    GitHub_BranchName_Disallowed:
    - master
