#
# Dependabot configuration
#

# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    labels:
      - ci-quality
    reviewers:
      - microsoft/psrule-rules-github

  # Maintain dependencies for NuGet
  - package-ecosystem: nuget
    directory: '/'
    schedule:
      interval: daily
    labels:
      - dependencies
    reviewers:
      - microsoft/psrule-rules-github
    groups:
      # Group PowerShell packages that have inter-dependencies
      dev-powershell:
        patterns:
          - System.Management.Automation
          - Microsoft.PowerShell.SDK
      dev-testing:
        patterns:
          - xunit
          - xunit.runner.visualstudio
          - coverlet.collector
          - Microsoft.NET.Test.Sdk
    ignore:
      - dependency-name: gitversion.tool
