# Azure DevOps
# CI pipeline for PSRule.Rules.GitHub

variables:
  version: '0.1.0'
  buildConfiguration: 'Release'
  disable.coverage.autogenerate: 'true'
  imageName: 'ubuntu-18.04'

 # Use build number format, i.e. 0.1.0-B2007001
name: I$(date:yyMM)$(rev:rrr)

trigger: none
pr: none

resources:
  pipelines:
  - pipeline: CI
    source: 'PSRule.Rules.GitHub-CI'
    branch: main
    trigger:
      branches:
        include:
        - main

stages:

# Test pipeline
- stage: Test
  variables:
    skipComponentGovernanceDetection: 'true'
  jobs:

  - template: jobs/integrationContainer.yaml
    parameters:
      name: ps_7_ubuntu_18_04
      displayName: 'PowerShell 7.0 - ubuntu-18.04'
      imageName: mcr.microsoft.com/powershell
      imageTag: 7.0.3-ubuntu-18.04
