# Azure DevOps
# Pipeline to run integration tests for PSRule.Rules.GitHub

variables:
  buildConfiguration: 'Release'
  imageName: 'ubuntu-20.04'

resources:
  pipelines:
  - pipeline: CI
    source: 'PSRule.Rules.GitHub-CI'
    branch: main
    trigger:
      branches:
        include:
        - main

# Use build number format, i.e. I2007009
name: I$(date:yyMM)$(rev:rrr)

trigger: none
pr: none

stages:

# Test pipeline
- stage: Test
  variables:
    skipComponentGovernanceDetection: 'true'
  jobs:
  - template: jobs/integrationContainer.yaml
    parameters:
      name: gh_integration
      displayName: 'GitHub Integration Tests'
      imageName: mcr.microsoft.com/powershell
      imageTag: 7.2.2-ubuntu-20.04
