#
# Repository validation
#
name: Analyze
on:
- pull_request_target
jobs:
  analyze:
    name: Analyze repository
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Run PSRule analysis
      uses: Microsoft/ps-rule@main
